const WORKER_DECODE_TIMEOUT = 1000 * 16
const WORKER_DECODE_TIMEOUT_CAUSE = 'decode-timeout'
const WORKER_DECODE_FAILURE_CAUSE = 'decode-failure'
const WORKER_LOAD_FAILURE_CAUSE = 'worker-load-failure'
const WORKER_LOAD_TIMEOUT = 1000 * 32
const WORKER_LOAD_TIMEOUT_CAUSE = 'worker-load-timeout'

export {
    WORKER_DECODE_FAILURE_CAUSE,
    WORKER_DECODE_TIMEOUT,
    WORKER_DECODE_TIMEOUT_CAUSE,
    WORKER_LOAD_FAILURE_CAUSE,
    WORKER_LOAD_TIMEOUT,
    WORKER_LOAD_TIMEOUT_CAUSE,
}
